Added quick dist for Pod debugging

diff --git a/thstat b/thstat
--- a/thstat
+++ b/thstat
@@ -1,15 +1,18 @@
 #!/bin/bash
+thopJar=`ls thop*.jar`
+lanternaJar=`ls lanterna*.jar`
 
-SOURCE=`dirname ${BASH_SOURCE[0]}`
-
-thopJar=`ls $SOURCE/lib/thop*`
-lanternaJar=`ls $SOURCE/lib/lanterna*`
-
+# set this
 toolsJar=$JAVA_HOME/lib/tools.jar
-
-if [ -f $toolsJar ]; then
-    echo "tools.jar not found, your JAVA_HOME must point to a JDK not a JRE"
-    exit 1
+if [ ! -f $toolsJar ]; then
+	toolsJar=/usr/lib/jvm/default/lib/tools.jar
+	if [ ! -f $toolJar ]; then 
+		toolsJar=/usr/lib/jvm/java/lib
+		if [ ! -f $toolsJar ]; then
+		    echo "tools.jar not found, your JAVA_HOME must point to a JDK not a JRE"
+		    exit 1			
+		fi
+	fi
 fi
 
-java -cp $thopJar:$lanternaJar:$JAVA_HOME/lib/tools.jar com.ds.thop.Thstat $1
+java -cp $thopJar:$lanternaJar:$toolsJar com.ds.thop.Thstat $1
